### ISSUE TITLE
Hessian目前版本不支持序列化org.apache.hadoop.hbase.client.Result

### ISSUE THREAD

**Issue by SteNicholas** [alipay/sofa-rpc#294]
使用sofa-rpc提供hbase相关的查询服务，出现反序列化org.apache.hadoop.hbase.client.Result异常情况，经排查是因为Hessian目前版本不支持序列化org.apache.hadoop.hbase.client.Result，烦请帮忙看看是否是这样的情况，其中HBase版本是1.1.2，谢谢。
服务接口:
````
import java.util.List;
import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.client.Scan;
import org.apache.hadoop.hbase.client.Get;

import com.fiberhome.iface.portal.exceptions.PortalException;
import com.fiberhome.iface.portal.resource.VisitorAttribute;

public interface HBaseIfaceService {
	
	public Result doGet(VisitorAttribute va, String tableName, Get get) throws PortalException;
	
    public List<Result> doGets(VisitorAttribute va, String tableName, List<Get> gets) throws PortalException;
    
    public List<Result> doScan(VisitorAttribute va, String tableName, Scan scan) throws PortalException;    
}
````
服务端:
````
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class IfaceManager {
	
	public static final String PropertyFile = "application.properties";
	
	private static final Logger LOG = LoggerFactory.getLogger(IfaceManager.class);
	
	public static void main(String[] args) throws PortalException {
		
		IfaceConfig.parseProperty(PropertyFile);
		
		IfaceService ifaceService 
			= new IfaceService(IfaceConfig.LISTEN_PORT, IfaceConfig.PROTOCOL, 
					IfaceConfig.CORE_THREADS, IfaceConfig.MAX_THREADS);

		hbaseProviderConfig = new ProviderConfig<HBaseIfaceService>()
	            .setInterfaceId(HBaseIfaceService.class.getName()) 
	            .setRef(new HBaseIfaceServiceImpl()) 
	            .setServer(serverConfig); 

		hbaseProviderConfig.export();
		
		LOG.info("Started interface server.");
	}
}
````
客户端:
````
import com.alipay.sofa.rpc.codec.AbstractSerializer;
import com.alipay.sofa.rpc.config.ConsumerConfig;
import com.alipay.sofa.rpc.core.exception.SofaRpcException;
import com.alipay.sofa.rpc.transport.AbstractByteBuf;

import org.apache.hadoop.hbase.Cell;
import org.apache.hadoop.hbase.client.Get;
import org.apache.hadoop.hbase.client.Result;
import org.apache.hadoop.hbase.client.Scan;
import org.apache.hadoop.hbase.util.Bytes;
import sun.awt.SunHints;

import java.util.List;
import java.util.Map;

public class IfaceClient {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String addr = "127.0.0.1:12200";  // server address for rpc 
		if(args.length == 1) {
			addr = args[0];
		}

		ConsumerConfig<HBaseIfaceService> consumerConfig = new ConsumerConfig<HBaseIfaceService>()
                .setInterfaceId(HBaseIfaceService.class.getName()) 
                .setProtocol("bolt") 
                .setDirectUrl("bolt://" + addr) 
                .setConnectTimeout(10 * 1000);

		HBaseIfaceService hIfaceService = consumerConfig.refer();

		try {
			String tableName = "tbl3";  // tableName
			String startRowKey = "abc-123"; // start row key
			String endRowKey = "abc-456";   // end row key
			Scan scan = new Scan(Bytes.toBytes(startRowKey), Bytes.toBytes(endRowKey));
//			String rowKeyPrefix = "abc-efg";    // prefix of row key
//	    	scan.setRowPrefixFilter(Bytes.toBytes(rowKeyPrefix));

	        List<Result> rs = hIfaceService.doScan(
	        		new VisitorAttribute("fiberman1", "yunchuang1", "HBaseTbl3GetCf2", "0.1"), tableName, scan);
	        for(Result res:rs){

	          byte[] a= res.getValue("url".getBytes(),"f".getBytes());
	            System.out.print(a.toString());
            }
	    } catch (Exception e) {
	        e.printStackTrace();
	    }
//        try {
//            String tableName = "tbl3";    // table name
//            byte[] rowkey = Bytes.toBytes("abc-123"); // string of rowkey
//            Get get = new Get(rowkey);
//           // get.addFamily(Bytes.toBytes("url"));  // column family
//            get.addColumn(Bytes.toBytes("url"), Bytes.toBytes("f")); // column and family
//            Result r = hIfaceService.doGet(new VisitorAttribute("fiberman", "yunchuang", "getfromtabletest", "v0.1"),
//                    tableName, get);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
	}
}
````
异常日志:
````
"D:\Program Files\Java\jdk1.8.0_131\bin\java" "-javaagent:D:\Program Files\JetBrains\ideaIU-2017.1.2\lib\idea_rt.jar=10338:D:\Program Files\JetBrains\ideaIU-2017.1.2\bin" -Dfile.encoding=UTF-8 -classpath "D:\Program Files\Java\jdk1.8.0_131\jre\lib\charsets.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\deploy.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\access-bridge-64.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\cldrdata.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\dnsns.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jaccess.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\jfxrt.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\localedata.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\nashorn.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunec.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunjce_provider.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunmscapi.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\sunpkcs11.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\ext\zipfs.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\javaws.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\jce.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\jfr.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\jfxswt.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\jsse.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\management-agent.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\plugin.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\resources.jar;D:\Program Files\Java\jdk1.8.0_131\jre\lib\rt.jar;F:\WorkSpace\iface_portal\iface_test\target\classes;F:\WorkSpace\iface_portal\iface_common\target\classes;D:\Users\hadoop\.m2\repository\org\apache\maven\plugins\maven-deploy-plugin\2.7\maven-deploy-plugin-2.7.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-plugin-api\2.0.6\maven-plugin-api-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-project\2.0.6\maven-project-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-settings\2.0.6\maven-settings-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-profile\2.0.6\maven-profile-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-artifact-manager\2.0.6\maven-artifact-manager-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-repository-metadata\2.0.6\maven-repository-metadata-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\wagon\wagon-provider-api\1.0-beta-2\wagon-provider-api-1.0-beta-2.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-plugin-registry\2.0.6\maven-plugin-registry-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\codehaus\plexus\plexus-container-default\1.0-alpha-9-stable-1\plexus-container-default-1.0-alpha-9-stable-1.jar;D:\Users\hadoop\.m2\repository\classworlds\classworlds\1.1-alpha-2\classworlds-1.1-alpha-2.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-model\2.0.6\maven-model-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\apache\maven\maven-artifact\2.0.6\maven-artifact-2.0.6.jar;D:\Users\hadoop\.m2\repository\org\codehaus\plexus\plexus-utils\1.5.6\plexus-utils-1.5.6.jar;D:\Users\hadoop\.m2\repository\com\alipay\sofa\sofa-rpc-all\5.4.3\sofa-rpc-all-5.4.3.jar;D:\Users\hadoop\.m2\repository\com\alipay\sofa\bolt\1.4.2\bolt-1.4.2.jar;D:\Users\hadoop\.m2\repository\com\alipay\sofa\common\sofa-common-tools\1.0.12\sofa-common-tools-1.0.12.jar;D:\Users\hadoop\.m2\repository\org\slf4j\slf4j-api\1.7.21\slf4j-api-1.7.21.jar;D:\Users\hadoop\.m2\repository\org\javassist\javassist\3.20.0-GA\javassist-3.20.0-GA.jar;D:\Users\hadoop\.m2\repository\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;D:\Users\hadoop\.m2\repository\com\alipay\sofa\hessian\3.3.2\hessian-3.3.2.jar;D:\Users\hadoop\.m2\repository\com\alipay\sofa\tracer-core\2.1.1\tracer-core-2.1.1.jar;D:\Users\hadoop\.m2\repository\io\opentracing\opentracing-api\0.22.0\opentracing-api-0.22.0.jar;D:\Users\hadoop\.m2\repository\io\opentracing\opentracing-noop\0.22.0\opentracing-noop-0.22.0.jar;D:\Users\hadoop\.m2\repository\io\opentracing\opentracing-mock\0.22.0\opentracing-mock-0.22.0.jar;D:\Users\hadoop\.m2\repository\io\opentracing\opentracing-util\0.22.0\opentracing-util-0.22.0.jar;D:\Users\hadoop\.m2\repository\org\jboss\resteasy\resteasy-netty4\3.0.12.Final\resteasy-netty4-3.0.12.Final.jar;D:\Users\hadoop\.m2\repository\org\jboss\resteasy\resteasy-jaxrs\3.0.12.Final\resteasy-jaxrs-3.0.12.Final.jar;D:\Users\hadoop\.m2\repository\org\jboss\resteasy\jaxrs-api\3.0.12.Final\jaxrs-api-3.0.12.Final.jar;D:\Users\hadoop\.m2\repository\org\jboss\spec\javax\annotation\jboss-annotations-api_1.1_spec\1.0.1.Final\jboss-annotations-api_1.1_spec-1.0.1.Final.jar;D:\Users\hadoop\.m2\repository\javax\activation\activation\1.1.1\activation-1.1.1.jar;D:\Users\hadoop\.m2\repository\net\jcip\jcip-annotations\1.0\jcip-annotations-1.0.jar;D:\Users\hadoop\.m2\repository\org\jboss\resteasy\resteasy-client\3.0.12.Final\resteasy-client-3.0.12.Final.jar;D:\Users\hadoop\.m2\repository\org\jboss\resteasy\resteasy-jackson-provider\3.0.12.Final\resteasy-jackson-provider-3.0.12.Final.jar;D:\Users\hadoop\.m2\repository\org\codehaus\jackson\jackson-core-asl\1.9.12\jackson-core-asl-1.9.12.jar;D:\Users\hadoop\.m2\repository\org\codehaus\jackson\jackson-jaxrs\1.9.12\jackson-jaxrs-1.9.12.jar;D:\Users\hadoop\.m2\repository\org\codehaus\jackson\jackson-xc\1.9.12\jackson-xc-1.9.12.jar;D:\Users\hadoop\.m2\repository\com\alipay\sofa\lookout\lookout-api\1.4.1\lookout-api-1.4.1.jar;D:\Users\hadoop\.m2\repository\org\apache\httpcomponents\httpcore\4.4.10\httpcore-4.4.10.jar;D:\Users\hadoop\.m2\repository\mysql\mysql-connector-java\5.1.25\mysql-connector-java-5.1.25.jar;D:\Users\hadoop\.m2\repository\org\apache\hbase\hbase-common\1.1.2\hbase-common-1.1.2.jar;D:\Users\hadoop\.m2\repository\org\apache\hbase\hbase-protocol\1.1.2\hbase-protocol-1.1.2.jar;D:\Users\hadoop\.m2\repository\org\apache\hbase\hbase-annotations\1.1.2\hbase-annotations-1.1.2.jar;D:\Program Files\Java\jdk1.8.0_131\lib\tools.jar;D:\Users\hadoop\.m2\repository\com\google\guava\guava\12.0.1\guava-12.0.1.jar;D:\Users\hadoop\.m2\repository\com\google\code\findbugs\jsr305\1.3.9\jsr305-1.3.9.jar;D:\Users\hadoop\.m2\repository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\Users\hadoop\.m2\repository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;D:\Users\hadoop\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;D:\Users\hadoop\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;D:\Users\hadoop\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;D:\Users\hadoop\.m2\repository\com\google\protobuf\protobuf-java\2.5.0\protobuf-java-2.5.0.jar;D:\Users\hadoop\.m2\repository\org\mortbay\jetty\jetty-util\6.1.26\jetty-util-6.1.26.jar;D:\Users\hadoop\.m2\repository\org\apache\htrace\htrace-core\3.1.0-incubating\htrace-core-3.1.0-incubating.jar;D:\Users\hadoop\.m2\repository\org\apache\hadoop\hadoop-common\2.5.1\hadoop-common-2.5.1.jar;D:\Users\hadoop\.m2\repository\org\apache\hadoop\hadoop-annotations\2.5.1\hadoop-annotations-2.5.1.jar;D:\Users\hadoop\.m2\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar;D:\Users\hadoop\.m2\repository\org\apache\commons\commons-math3\3.1.1\commons-math3-3.1.1.jar;D:\Users\hadoop\.m2\repository\xmlenc\xmlenc\0.52\xmlenc-0.52.jar;D:\Users\hadoop\.m2\repository\commons-httpclient\commons-httpclient\3.1\commons-httpclient-3.1.jar;D:\Users\hadoop\.m2\repository\commons-net\commons-net\3.1\commons-net-3.1.jar;D:\Users\hadoop\.m2\repository\org\mortbay\jetty\jetty\6.1.26\jetty-6.1.26.jar;D:\Users\hadoop\.m2\repository\com\sun\jersey\jersey-core\1.9\jersey-core-1.9.jar;D:\Users\hadoop\.m2\repository\com\sun\jersey\jersey-json\1.9\jersey-json-1.9.jar;D:\Users\hadoop\.m2\repository\org\codehaus\jettison\jettison\1.1\jettison-1.1.jar;D:\Users\hadoop\.m2\repository\com\sun\xml\bind\jaxb-impl\2.2.3-1\jaxb-impl-2.2.3-1.jar;D:\Users\hadoop\.m2\repository\com\sun\jersey\jersey-server\1.9\jersey-server-1.9.jar;D:\Users\hadoop\.m2\repository\asm\asm\3.1\asm-3.1.jar;D:\Users\hadoop\.m2\repository\tomcat\jasper-compiler\5.5.23\jasper-compiler-5.5.23.jar;D:\Users\hadoop\.m2\repository\tomcat\jasper-runtime\5.5.23\jasper-runtime-5.5.23.jar;D:\Users\hadoop\.m2\repository\commons-el\commons-el\1.0\commons-el-1.0.jar;D:\Users\hadoop\.m2\repository\net\java\dev\jets3t\jets3t\0.9.0\jets3t-0.9.0.jar;D:\Users\hadoop\.m2\repository\com\jamesmurty\utils\java-xmlbuilder\0.4\java-xmlbuilder-0.4.jar;D:\Users\hadoop\.m2\repository\commons-configuration\commons-configuration\1.6\commons-configuration-1.6.jar;D:\Users\hadoop\.m2\repository\commons-digester\commons-digester\1.8\commons-digester-1.8.jar;D:\Users\hadoop\.m2\repository\commons-beanutils\commons-beanutils\1.7.0\commons-beanutils-1.7.0.jar;D:\Users\hadoop\.m2\repository\commons-beanutils\commons-beanutils-core\1.8.0\commons-beanutils-core-1.8.0.jar;D:\Users\hadoop\.m2\repository\org\slf4j\slf4j-log4j12\1.7.5\slf4j-log4j12-1.7.5.jar;D:\Users\hadoop\.m2\repository\org\apache\avro\avro\1.7.4\avro-1.7.4.jar;D:\Users\hadoop\.m2\repository\com\thoughtworks\paranamer\paranamer\2.3\paranamer-2.3.jar;D:\Users\hadoop\.m2\repository\org\xerial\snappy\snappy-java\1.0.4.1\snappy-java-1.0.4.1.jar;D:\Users\hadoop\.m2\repository\com\jcraft\jsch\0.1.42\jsch-0.1.42.jar;D:\Users\hadoop\.m2\repository\org\apache\commons\commons-compress\1.4.1\commons-compress-1.4.1.jar;D:\Users\hadoop\.m2\repository\org\tukaani\xz\1.0\xz-1.0.jar;D:\Users\hadoop\.m2\repository\org\apache\hadoop\hadoop-mapreduce-client-core\2.5.1\hadoop-mapreduce-client-core-2.5.1.jar;D:\Users\hadoop\.m2\repository\org\apache\hadoop\hadoop-yarn-common\2.5.1\hadoop-yarn-common-2.5.1.jar;D:\Users\hadoop\.m2\repository\org\apache\hadoop\hadoop-yarn-api\2.5.1\hadoop-yarn-api-2.5.1.jar;D:\Users\hadoop\.m2\repository\javax\xml\bind\jaxb-api\2.2.2\jaxb-api-2.2.2.jar;D:\Users\hadoop\.m2\repository\javax\xml\stream\stax-api\1.0-2\stax-api-1.0-2.jar;D:\Users\hadoop\.m2\repository\javax\servlet\servlet-api\2.5\servlet-api-2.5.jar;D:\Users\hadoop\.m2\repository\com\google\inject\guice\3.0\guice-3.0.jar;D:\Users\hadoop\.m2\repository\javax\inject\javax.inject\1\javax.inject-1.jar;D:\Users\hadoop\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;D:\Users\hadoop\.m2\repository\com\sun\jersey\contribs\jersey-guice\1.9\jersey-guice-1.9.jar;D:\Users\hadoop\.m2\repository\com\google\inject\extensions\guice-servlet\3.0\guice-servlet-3.0.jar;D:\Users\hadoop\.m2\repository\com\github\stephenc\findbugs\findbugs-annotations\1.3.9-1\findbugs-annotations-1.3.9-1.jar;D:\Users\hadoop\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;D:\Users\hadoop\.m2\repository\org\apache\hbase\hbase-client\1.1.2\hbase-client-1.1.2.jar;D:\Users\hadoop\.m2\repository\org\apache\zookeeper\zookeeper\3.4.6\zookeeper-3.4.6.jar;D:\Users\hadoop\.m2\repository\org\codehaus\jackson\jackson-mapper-asl\1.9.13\jackson-mapper-asl-1.9.13.jar;D:\Users\hadoop\.m2\repository\org\jruby\jcodings\jcodings\1.0.8\jcodings-1.0.8.jar;D:\Users\hadoop\.m2\repository\org\jruby\joni\joni\2.1.2\joni-2.1.2.jar;D:\Users\hadoop\.m2\repository\org\apache\hadoop\hadoop-auth\2.5.1\hadoop-auth-2.5.1.jar;D:\Users\hadoop\.m2\repository\org\apache\httpcomponents\httpclient\4.2.5\httpclient-4.2.5.jar;D:\Users\hadoop\.m2\repository\org\apache\directory\server\apacheds-kerberos-codec\2.0.0-M15\apacheds-kerberos-codec-2.0.0-M15.jar;D:\Users\hadoop\.m2\repository\org\apache\directory\server\apacheds-i18n\2.0.0-M15\apacheds-i18n-2.0.0-M15.jar;D:\Users\hadoop\.m2\repository\org\apache\directory\api\api-asn1-api\1.0.0-M20\api-asn1-api-1.0.0-M20.jar;D:\Users\hadoop\.m2\repository\org\apache\directory\api\api-util\1.0.0-M20\api-util-1.0.0-M20.jar" com.my.iface.portal.IfaceClient
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.sofa.rpc Log4j ]
log4j:WARN No appenders could be found for logger (com.alipay.sofa.common.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:ERROR Failed to rename [C:\Users\hadoop\logs/rpc//rpc-client.log] to [C:\Users\hadoop\logs/rpc//rpc-client.log.2018-09-03].
Sofa-Middleware-Log SLF4J : Actual binding is of type [ com.alipay.remoting Log4j ]
log4j:ERROR Failed to rename [C:\Users\hadoop\logs/bolt/connection-event.log] to [C:\Users\hadoop\logs/bolt/connection-event.log.2018-09-03].
C:\Users\hadoop\logs\tracelog\middleware_error.log -> C:\Users\hadoop\logs\tracelog\middleware_error.log.2018-09-03
C:\Users\hadoop\logs\tracelog\rpc-client-digest.log -> C:\Users\hadoop\logs\tracelog\rpc-client-digest.log.2018-09-03
com.alipay.sofa.rpc.core.exception.SofaRpcException: com.alipay.remoting.exception.DeserializationException: org.apache.hadoop.hbase.client.Result.cells: [Ljava.lang.Object; ([Ljava.lang.Object;@5cee5251) cannot be assigned to [Lorg.apache.hadoop.hbase.Cell;
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.convertToRpcException(BoltClientTransport.java:356)
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.syncSend(BoltClientTransport.java:265)
	at com.alipay.sofa.rpc.client.AbstractCluster.doSendMsg(AbstractCluster.java:509)
	at com.alipay.sofa.rpc.client.AbstractCluster.sendMsg(AbstractCluster.java:480)
	at com.alipay.sofa.rpc.filter.ConsumerInvoker.invoke(ConsumerInvoker.java:60)
	at com.alipay.sofa.rpc.filter.sofatracer.ConsumerTracerFilter.invoke(ConsumerTracerFilter.java:66)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
	at com.alipay.sofa.rpc.filter.RpcReferenceContextFilter.invoke(RpcReferenceContextFilter.java:80)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
	at com.alipay.sofa.rpc.filter.ConsumerExceptionFilter.invoke(ConsumerExceptionFilter.java:37)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
	at com.alipay.sofa.rpc.filter.FilterChain.invoke(FilterChain.java:299)
	at com.alipay.sofa.rpc.client.AbstractCluster.filterChain(AbstractCluster.java:473)
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:66)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:285)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
	at com.my.iface.portal.service.HBaseIfaceService_proxy_0.doScan(HBaseIfaceService_proxy_0.java)
	at com.my.iface.portal.IfaceClient.main(IfaceClient.java:45)
Caused by: com.alipay.remoting.exception.DeserializationException: org.apache.hadoop.hbase.client.Result.cells: [Ljava.lang.Object; ([Ljava.lang.Object;@5cee5251) cannot be assigned to [Lorg.apache.hadoop.hbase.Cell;
	at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.deserializeContent(SofaRpcSerialization.java:367)
	at com.alipay.remoting.rpc.protocol.RpcResponseCommand.deserializeContent(RpcResponseCommand.java:129)
	at com.alipay.remoting.rpc.RpcCommand.deserialize(RpcCommand.java:117)
	at com.alipay.remoting.rpc.RpcResponseResolver.toResponseObject(RpcResponseResolver.java:159)
	at com.alipay.remoting.rpc.RpcResponseResolver.resolveResponseObject(RpcResponseResolver.java:59)
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:186)
	at com.alipay.remoting.rpc.RpcClientRemoting.invokeSync(RpcClientRemoting.java:67)
	at com.alipay.remoting.rpc.RpcClient.invokeSync(RpcClient.java:350)
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.doInvokeSync(BoltClientTransport.java:289)
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.syncSend(BoltClientTransport.java:262)
	... 16 more
Caused by: com.alipay.sofa.rpc.core.exception.SofaRpcException: org.apache.hadoop.hbase.client.Result.cells: [Ljava.lang.Object; ([Ljava.lang.Object;@5cee5251) cannot be assigned to [Lorg.apache.hadoop.hbase.Cell;
	at com.alipay.sofa.rpc.codec.AbstractSerializer.buildDeserializeError(AbstractSerializer.java:41)
	at com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer.decodeSofaResponseByTemplate(SofaHessianSerializer.java:368)
	at com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer.decode(SofaHessianSerializer.java:213)
	at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.deserializeContent(SofaRpcSerialization.java:362)
	... 25 more
Caused by: com.caucho.hessian.io.HessianFieldException: org.apache.hadoop.hbase.client.Result.cells: [Ljava.lang.Object; ([Ljava.lang.Object;@5cee5251) cannot be assigned to [Lorg.apache.hadoop.hbase.Cell;
	at com.caucho.hessian.io.JavaDeserializer.logDeserializeError(JavaDeserializer.java:623)
	at com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:421)
	at com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:253)
	at com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:177)
	at com.caucho.hessian.io.SerializerFactory.readObject(SerializerFactory.java:362)
	at com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2763)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2675)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2667)
	at com.caucho.hessian.io.CollectionDeserializer.readList(CollectionDeserializer.java:78)
	at com.caucho.hessian.io.SerializerFactory.readList(SerializerFactory.java:329)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2638)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2201)
	at com.caucho.hessian.io.JavaDeserializer$ObjectFieldDeserializer.deserialize(JavaDeserializer.java:417)
	at com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:253)
	at com.caucho.hessian.io.JavaDeserializer.readObject(JavaDeserializer.java:177)
	at com.caucho.hessian.io.SerializerFactory.readObject(SerializerFactory.java:362)
	at com.caucho.hessian.io.Hessian2Input.readObjectInstance(Hessian2Input.java:2763)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2675)
	at com.caucho.hessian.io.Hessian2Input.readObject(Hessian2Input.java:2667)
	at com.alipay.sofa.rpc.codec.sofahessian.SofaHessianSerializer.decodeSofaResponseByTemplate(SofaHessianSerializer.java:360)
	... 27 more
````

**Comment by leizhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2684384/45030766-8136fd80-b07f-11e8-9f8b-20eb373da56f.png)

最简的复现代码。

```
public static void main(String[] args) {

        Cell[] cells = new Cell[1];
        cells[0] = new KeyValue();
        Result result = Result.create(cells);

        try {
            ByteArrayOutputStream bout = new ByteArrayOutputStream();
            Hessian2Output h2out = new Hessian2Output(bout);

            h2out.setSerializerFactory(new SingleClassLoaderSofaSerializerFactory());
            h2out.writeObject(result);

            h2out.flush();
            byte[] body = bout.toByteArray();


            System.out.println(Arrays.toString(body));

            ByteArrayInputStream input = new ByteArrayInputStream(body, 0, body.length);
            Hessian2Input hin = new Hessian2Input(input);

            System.out.println(hin.readObject().getClass());


        } catch (Exception e) {
            e.printStackTrace();
        }

    }
```

复现代码如上。hessian 反序列化的时候，读到的是 Object 类型，反射设置的时候，这里是无法识别出来。hessian4应该也是这样的。

**Comment by leizhiyuan** [comment]
我测试了一下，hessian4 是支持的。

https://github.com/alipay/sofa-rpc/issues/217 可以参考这里的临时改下验证下。

**Comment by SteNicholas** [comment]
@ujjboy Thank you.I try it.
