### ISSUE TITLE
sofa中调用dubbo的问题请教

### ISSUE THREAD

**Issue by eva233man** [alipay/sofa-rpc#312]
我在sofa中使用ConsumerConfig生成GenericService调用dubbo，但是报下面的错，应该是版本的问题，服务端dubbo服务并没有指定版本号
com.alibaba.dubbo.rpc.RpcException: No provider available from registry XX.X.16.6:2181 for service com.XXX.XXX.XXX.common.dubbo.DubboInterface:1.0 on consumer XX.X.40.1 use dubbo version 2.6.0, may be providers disabled or not registered ?
at com.alibaba.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:572)
at com.alibaba.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:73)
at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:265)
at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:224)
at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70)
at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51)
at com.alibaba.dubbo.common.bytecode.proxy0.$invoke(proxy0.java)

我看见代码里在转换dubbo调用的时候，写死设置了1.0，请问下这是基于什么考虑？
referenceConfig.setVersion("1.0");

**Comment by ujjboy** [comment]
只是为了兼容dubbo协议。 
dubbo 是通过接口+协议+ group+ version 作为关键字，且version不能为空。
而 sofa-rpc里是通过 接口+协议+uniqueId 作为关键。我们将 uniqueId 映射到了 group， version 则保留一个兼容值。

**Comment by ujjboy** [comment]
@eva233man 你是想泛化调一个现有的dubbo服务？  还是调一个 sofa-rpc 发布的 dubbo 服务？

**Comment by eva233man** [comment]
@ujjboy 泛化调用一个现有的dubbo服务，但是并没有设置版本号
为啥不可以设置为*

**Comment by ujjboy** [comment]
设置为 `*`  的话，我印象里只在有服务注册中心的场景下生效，这个得验证下。 

方便的话，你可以直接修改 `DubboProviderBootstrap` 和 `DubboConsumerBootstrap` 里的相关逻辑测试下。

也可以提交相关PR。

**Comment by qinliang373** [comment]
这个问题也遇到了

**Comment by leizhiyuan** [comment]
@qinliang373 @eva233man 能否提供一个可复现的 demo? 我们这边验证修复下
