### ISSUE TITLE
使用已有扩展点获取sofarpc内部的一些连接情况报错

### ISSUE THREAD

**Issue by sohoku** [alipay/sofa-rpc#361]
ConnectionHolder all = ExtensionLoaderFactory.getExtensionLoader(ConnectionHolder.class).getExtension("all");

![image](https://user-images.githubusercontent.com/5020217/48190688-4ce10580-e37e-11e8-91fa-ed953c1e021e.png)
`com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: create com.alipay.sofa.rpc.client.AllConnectConnectionHolder instance error
        at com.alipay.sofa.rpc.ext.ExtensionClass.getExtInstance(ExtensionClass.java:115)
        at com.alipay.sofa.rpc.ext.ExtensionClass.getExtInstance(ExtensionClass.java:89)
        at com.alipay.sofa.rpc.ext.ExtensionLoader.getExtension(ExtensionLoader.java:436)
        at com.zb.game.processor.GoRequestServiceImpl.handlerMove(GoRequestServiceImpl.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.alipay.sofa.rpc.filter.ProviderInvoker.invoke(ProviderInvoker.java:77)
        at com.alipay.sofa.rpc.filter.sofatracer.ProviderTracerFilter.invoke(ProviderTracerFilter.java:74)
        at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
        at com.alipay.sofa.rpc.filter.ProviderBaggageFilter.invoke(ProviderBaggageFilter.java:45)
        at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
        at com.alipay.sofa.rpc.filter.RpcServiceContextFilter.invoke(RpcServiceContextFilter.java:62)
        at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
        at com.alipay.sofa.rpc.filter.ProviderExceptionFilter.invoke(ProviderExceptionFilter.java:37)
        at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
        at com.alipay.sofa.rpc.filter.FilterChain.invoke(FilterChain.java:302)
        at com.alipay.sofa.rpc.server.ProviderProxyInvoker.invoke(ProviderProxyInvoker.java:65)
        at com.alipay.sofa.rpc.server.bolt.BoltServerProcessor.doInvoke(BoltServerProcessor.java:226)
        at com.alipay.sofa.rpc.server.bolt.BoltServerProcessor.handleRequest(BoltServerProcessor.java:171)
        at com.alipay.sofa.rpc.server.bolt.BoltServerProcessor.handleRequest(BoltServerProcessor.java:61)
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.dispatchToUserProcessor(RpcRequestProcessor.java:218)
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor.doProcess(RpcRequestProcessor.java:145)
        at com.alipay.remoting.rpc.protocol.RpcRequestProcessor$ProcessTask.run(RpcRequestProcessor.java:371)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: null
        at com.alipay.sofa.rpc.common.utils.ClassUtils.newInstance(ClassUtils.java:181)
        at com.alipay.sofa.rpc.common.utils.ClassUtils.newInstanceWithArgs(ClassUtils.java:198)
        at com.alipay.sofa.rpc.ext.ExtensionClass.getExtInstance(ExtensionClass.java:112)
        ... 27 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor72.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at com.alipay.sofa.rpc.common.utils.ClassUtils.newInstance(ClassUtils.java:177)
        ... 29 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.alipay.sofa.rpc.client.AllConnectConnectionHolder.<init>(AllConnectConnectionHolder.java:79)
        ... 33 common frames omitted`

同样的，我试着获取默认的zookeeper，虽然得到了对象，但是值为空：
![image](https://user-images.githubusercontent.com/5020217/48190958-f627fb80-e37e-11e8-99c6-96ec13a2911a.png)

_Originally posted by @sohoku in https://github.com/alipay/sofa-rpc/issues/322#issuecomment-436935423_

**Comment by JervyShi** [comment]
`ExtensionLoaderFactory` 主要处理 RPC 的模块加载，这里不一定会保存所有的实例化对象，类似 Registry 这种，是可能存在多个的，每个独立的 `RegistryConfig` 都对应一个 `Registry` 实例，参见：`com.alipay.sofa.rpc.registry.RegistryFactory`。
`ConnectionHolder` 类似，是一个服务消费者会对应一个实例的，参见：`com.alipay.sofa.rpc.client.ConnectionHolderFactory`。

**Comment by leizhiyuan** [comment]
这个是扩展,实例化对象不会保存,因为不会限制用户使用多少个

如果是 SOFABoot 环境,有对应的 holder 可以获取.

RegistryConfigContainer 可以 autowared 注入
