### ISSUE TITLE
RestTracerTest 单元测试无法通过 

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#379]
### Describe the bug

RestTracerTest 单元测试无法通过 

### Steps to reproduce
单独运行 RestTracerTest 可以通过
同时运行 com.alipay.sofa.rpc.server.rest 包下所有测试不能通过:

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at com.alipay.sofa.rpc.server.rest.RestTracerTest.reflectToTracer(RestTracerTest.java:179)
	at com.alipay.sofa.rpc.server.rest.RestTracerTest.testRestTracer(RestTracerTest.java:68)
```
debug 显示 clientReporter 类型为 DiskReporterImpl 
```java
  assertTrue(clientReporter instanceof MemoryReporterImpl);
```

### Environment

- SOFARPC version:5.4.8-SNAPSHOT 
- JVM version (e.g. `java -version`): jdk1.8.0_111
- OS version (e.g. `uname -a`):  osx
- Maven version: jdk1.8.0_111
- IDE version:

**Comment by leizhiyuan** [comment]
https://github.com/alipay/sofa-rpc/pull/370 这个 pr 还没有合并。合并后会 ok

**Comment by leizhiyuan** [comment]
已经合并，麻烦再验证下。issue 先关闭了。有问题麻烦再打开~
