### ISSUE TITLE
JDK10 运行ZK注册中心实例netty出现异常

### ISSUE THREAD

**Issue by VincentSleepless** [alipay/sofa-rpc#447]
### Your question
JDK10 运行ZK注册中心实例netty出现异常

### Your scenes
异常日志
-----------------------------------------------------------------------------------------------------------
18:23:08.084 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
18:23:08.115 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
18:23:08.115 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
18:23:08.115 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 10
18:23:08.130 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
18:23:08.130 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
18:23:08.130 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
18:23:08.130 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:261)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:143)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at com.alipay.remoting.rpc.RpcServer.<clinit>(RpcServer.java:116)
	at com.alipay.sofa.rpc.server.bolt.BoltServer.initRemotingServer(BoltServer.java:139)
	at com.alipay.sofa.rpc.server.bolt.BoltServer.start(BoltServer.java:113)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.doExport(DefaultProviderBootstrap.java:178)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.export(DefaultProviderBootstrap.java:105)
	at com.alipay.sofa.rpc.config.ProviderConfig.export(ProviderConfig.java:524)
	at com.za.sirius.baffle.portal.service.hello.HelloServiceServer.main(HelloServiceServer.java:44)
18:23:08.130 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: unavailable true
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:273)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:266)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:261)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:143)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at com.alipay.remoting.rpc.RpcServer.<clinit>(RpcServer.java:116)
	at com.alipay.sofa.rpc.server.bolt.BoltServer.initRemotingServer(BoltServer.java:139)
	at com.alipay.sofa.rpc.server.bolt.BoltServer.start(BoltServer.java:113)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.doExport(DefaultProviderBootstrap.java:178)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.export(DefaultProviderBootstrap.java:105)
	at com.alipay.sofa.rpc.config.ProviderConfig.export(ProviderConfig.java:524)
	at com.za.sirius.baffle.portal.service.hello.HelloServiceServer.main(HelloServiceServer.java:44)
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @299321e2
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:360)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:315)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:306)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:261)
	at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
	at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:143)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at com.alipay.remoting.rpc.RpcServer.<clinit>(RpcServer.java:116)
	at com.alipay.sofa.rpc.server.bolt.BoltServer.initRemotingServer(BoltServer.java:139)
	at com.alipay.sofa.rpc.server.bolt.BoltServer.start(BoltServer.java:113)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.doExport(DefaultProviderBootstrap.java:178)
	at com.alipay.sofa.rpc.bootstrap.DefaultProviderBootstrap.export(DefaultProviderBootstrap.java:105)
	at com.alipay.sofa.rpc.config.ProviderConfig.export(ProviderConfig.java:524)
	at com.za.sirius.baffle.portal.service.hello.HelloServiceServer.main(HelloServiceServer.java:44)
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 1994391552 bytes (maybe)
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\zengli\AppData\Local\Temp (java.io.tmpdir)
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
18:23:08.146 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
18:23:08.146 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
18:23:08.177 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
18:23:10.178 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
18:23:10.178 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
18:23:10.225 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 6956 (auto-detected)
18:23:10.225 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
18:23:10.225 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
18:23:11.556 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
18:23:11.556 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
18:23:12.968 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 28:16:ad:ff:fe:f1:e5:1e (auto-detected)
18:23:12.983 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
18:23:12.983 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
18:23:13.030 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
18:23:13.061 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
18:23:13.061 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
18:23:13.061 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
18:23:13.329 [main] INFO org.apache.curator.utils.Compatibility - Running in ZooKeeper 3.4.x compatibility mode
18:23:13.422 [main] INFO org.apache.curator.framework.imps.CuratorFrameworkImpl - Starting

### Your advice

因为做分布式调度平台的进程处理相关代码需要用到java9+以上，所以想看一下sofa的支持，以便模块之间的接口通信。

### Environment

- SOFARPC version:5.4.8
- JVM version (e.g. `java -version`): openjdk 10.0.2
- OS version (e.g. `uname -a`): windows
- Maven version: 3.2.2
- IDE version: intellj 2018

**Comment by VincentSleepless** [comment]
> 似乎是目前的netty版本不支持jdk10

降到jdk9 有没有可能
