### ISSUE TITLE
服务端变动 IP 时,客户端会连接向已经下线的服务

### ISSUE THREAD

**Issue by OrezzerO** [alipay/sofa-rpc#486]
### Describe the bug
服务端是sofa boot+sofa rpc 使用 bolt 协议暴露的服务,客户端是api 建立的客户端: 
```
 RegistryConfig registryConfig = new RegistryConfig().setProtocol("zookeeper").setAddress("xxxx");
 ConsumerConfig consumerConfig = new ConsumerConfig<HelloService().setInterfaceId(HelloService.class.getName()) // 指定接口
                .setProtocol("bolt") // 指定协议
                .setRegistry(registryConfig),
                .setInvokeType(RpcConstants.INVOKER_TYPE_ONEWAY); 
        HelloService helloService = (HelloService) consumerConfig.refer();
```
报错:
```
2019-01-15 17:08:23.344 [Rpc-netty-client-worker-1-thread-39] INFO  - Connection channel unregistered: UNKNOWN-ADDR
2019-01-15 17:08:23.345 [Rpc-netty-client-worker-1-thread-40] INFO  - Connection channel registered: UNKNOWN-ADDR
2019-01-15 17:08:23.345 [Rpc-netty-client-worker-1-thread-40] INFO  - Try connect to 10.5.63.27:12200
2019-01-15 17:08:24.318 [RpcTaskScannerThread] ERROR - Future task has not completed!
com.alipay.remoting.util.FutureTaskNotCompleted: null
	at com.alipay.remoting.util.RunStateRecordedFutureTask.getAfterRun(RunStateRecordedFutureTask.java:48)
	at com.alipay.remoting.util.FutureTaskUtil.getFutureTaskResult(FutureTaskUtil.java:43)
	at com.alipay.remoting.DefaultConnectionManager.getConnectionPool(DefaultConnectionManager.java:563)
	at com.alipay.remoting.DefaultConnectionManager.scan(DefaultConnectionManager.java:439)
	at com.alipay.remoting.rpc.RpcTaskScanner$2.run(RpcTaskScanner.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-01-15 17:08:26.347 [Rpc-netty-client-worker-1-thread-40] INFO  - Connection closed: UNKNOWN-ADDR
2019-01-15 17:08:26.347 [SOFA-CLI-RC-com.ppdai.proxy.api.LogServiceApi-2-T1] WARN  - Create connection to 10.5.63.27:12200 error!
2019-01-15 17:08:26.347 [Rpc-netty-client-worker-1-thread-40] INFO  - Connection channel unregistered: UNKNOWN-ADDR
2019-01-15 17:08:26.347 [Rpc-netty-client-worker-1-thread-41] INFO  - Connection channel registered: UNKNOWN-ADDR
2019-01-15 17:08:26.348 [Rpc-netty-client-worker-1-thread-41] INFO  - Try connect to 10.5.63.204:12200
```

这是同事给我的堆栈和代码,我本地没有能重现这个问题.

### Environment

- SOFARPC version: 5.4.8
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
如果zk没有推送过这个地址下线的信息，那么rpc还是会认为是一个地址，进行异步的重连

2019-01-15 17:08:26.347 [SOFA-CLI-RC-com.ppdai.proxy.api.LogServiceApi-2-T1] WARN  - Create connection to 10.5.63.27:12200 error!

看线程名，但是不会真正去调用，也不会影响业务。

**Comment by leizhiyuan** [comment]
没有问题先关闭了。
