### ISSUE TITLE
sofaboot-dependencies 3.0.0 SofaRpc报LEAK: ByteBuf.release() 错误。

### ISSUE THREAD

**Issue by liangpdu** [alipay/sofa-rpc#516]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

```
（Rpc-netty-client-worker-1-thread-3）LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information. Recent access records: Created at: io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331) io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185) 
```

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by leizhiyuan** [comment]
@liangpdu 

http://netty.io/wiki/reference-counted-objects.html 是 netty 自己有个引用计数,来追踪 buffer 的分配和回收
他发现有 buffer 分配了,但是没有手工清空等,就会打印这个日志
但是实际上, jvm gc 的时候,是能回收掉的.
如果你这边线下能稳定复现，辛苦加下`-Dio.netty.leakDetection.level=advanced` 这个启动参数.然后再出现的时候，会有详细的信息，可以帮助排查。

如果是线上，不要大面积加，可以挑一两台加一下。

注:此问题不会影响线上业务

**Comment by liangpdu** [comment]
好的，非常感谢。
1.我想确认下是否影响业务,不影响业务就放心了。
2.这个是线上出现的问题，不过现在量还不大。我加下JVM参数试试，复现了我找你帮忙看看

**Comment by leizhiyuan** [comment]
好的。
确定不会影响线上业务。这个我们线上也偶尔看到过。但是很难复现。

如果方便，可以挑一两台加下这个参数。会进行内存分配采样，最大会有5%的性能损失。一两台不会对你们的线上业务产生影响。

**Comment by leizhiyuan** [comment]
另外，方便的话，不知道你这边是哪家公司，是否可以邮件或者微信私聊下？

**Comment by liangpdu** [comment]
好的谢谢，微信号liangpvg

**Comment by liangpdu** [comment]
错误了 ，微信号lirongpvg

**Comment by xiaoming2624** [comment]
hi,@leizhiyuan,你好， 协议为h2的这个功能是不是没修复啊，也会出现类似这个问题，

 ERROR io.netty.util.ResourceLeakDetector.reportTracedLeak:320  LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:173)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
	com.alipay.sofa.rpc.transport.http.Http2ServerChannelHandler.onDataRead(Http2ServerChannelHandler.java:122)
	io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:292)
	io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
	io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59)
	io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
2020-12-08 10:22:26,909 WARN com.jinninghui.newspiral.p2p.impl.base.ServiceForPeerClient.addSDKTranscation:199  MODULE=SYSTEM_PLANTFORM_ACTION,调用sdkTransaction失败,异步系统，此异常并不会抛出，大部分情况下，对系统不会产生严重影响，channelId:C3B0C5727E1B425294039F99853BCDF6,clientTxId:clientTxIdEFC24AAD35944E4495B64CBD2DFC4F89，异常信息:
com.alipay.sofa.rpc.core.exception.SofaRouteException: RPC-020020009: 当前服务[com.jinninghui.newspiral.gateway.ServiceForPeer]的地址[h2://172.31.26.80:12200,]不可用,或指定的地址不在可用的地址列表中 
	at com.alipay.sofa.rpc.client.AbstractCluster.unavailableProviderException(AbstractCluster.java:500)
	at com.alipay.sofa.rpc.client.AbstractCluster.select(AbstractCluster.java:453)
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:65)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:297)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
	at com.jinninghui.newspiral.gateway.ServiceForPeer_proxy_1.addSDKTranscation(ServiceForPeer_proxy_1.java)
	at com.jinninghui.newspiral.p2p.impl.base.ServiceForPeerClient.addSDKTranscation(ServiceForPeerClient.java:195)
	at com.jinninghui.newspiral.p2p.impl.base.ChannelClientMgr.broadcastTransaction(ChannelClientMgr.java:116)
	at com.jinninghui.newspiral.p2p.impl.hotstuff.HotStuffRPC.broadcastTranscation(HotStuffRPC.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.runtime.service.binding.JvmBindingAdapter$JvmServiceInvoker.doInvoke(JvmBindingAdapter.java:201)
	at com.alipay.sofa.runtime.spi.service.ServiceProxy.invoke(ServiceProxy.java:40)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy120.broadcastTranscation(Unknown Source)
	at com.jinninghui.newspiral.transaction.mgr.impl.TransactionMgrImpl.broadcastTranscation(TransactionMgrImpl.java:141)
	at com.jinninghui.newspiral.transaction.mgr.impl.TransactionMgrImpl.addTransaction(TransactionMgrImpl.java:125)
	at sun.reflect.GeneratedMethodAccessor279.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.runtime.service.binding.JvmBindingAdapter$JvmServiceInvoker.doInvoke(JvmBindingAdapter.java:201)
	at com.alipay.sofa.runtime.spi.service.ServiceProxy.invoke(ServiceProxy.java:40)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy118.addTransaction(Unknown Source)
	at com.jinninghui.newspiral.gateway.ServiceForSDKImpl.callExecuteBusinessSmartContract(ServiceForSDKImpl.java:258)
	at com.jinninghui.newspiral.gateway.ServiceForSDKImpl$$FastClassBySpringCGLIB$$e94e6317.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.jinninghui.newspiral.gateway.aspect.InterfaceRecordAspect.addInterfaceRecordToQueue(InterfaceRecordAspect.java:236)
	at com.jinninghui.newspiral.gateway.aspect.InterfaceRecordAspect.RecordSdkCall(InterfaceRecordAspect.java:60)
	at sun.reflect.GeneratedMethodAccessor294.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at com.jinninghui.newspiral.gateway.aspect.ExceptionHandlerAspect.handleExc(ExceptionHandlerAspect.java:40)
	at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.jinninghui.newspiral.gateway.ServiceForSDKImpl$$EnhancerBySpringCGLIB$$ba987f3f.callExecuteBusinessSmartContract(<generated>)
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alipay.sofa.rpc.filter.ProviderInvoker.invoke(ProviderInvoker.java:100)
	at com.alipay.sofa.rpc.filter.sofatracer.ProviderTracerFilter.invoke(ProviderTracerFilter.java:74)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:100)
	at com.alipay.sofa.rpc.filter.ProviderBaggageFilter.invoke(ProviderBaggageFilter.java:45)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:100)
	at com.alipay.sofa.rpc.filter.RpcServiceContextFilter.invoke(RpcServiceContextFilter.java:62)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:100)
	at com.alipay.sofa.rpc.filter.ProviderExceptionFilter.invoke(ProviderExceptionFilter.java:37)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:100)
	at com.alipay.sofa.rpc.filter.FilterChain.invoke(FilterChain.java:268)
	at com.alipay.sofa.rpc.server.ProviderProxyInvoker.invoke(ProviderProxyInvoker.java:65)
	at com.alipay.sofa.rpc.server.http.AbstractHttpServerTask.doInvoke(AbstractHttpServerTask.java:223)
	at com.alipay.sofa.rpc.server.http.AbstractHttpServerTask.run(AbstractHttpServerTask.java:159)
	at com.alipay.sofa.rpc.server.http.HttpServerHandler.handleHttp2Request(HttpServerHandler.java:108)
	at com.alipay.sofa.rpc.transport.http.Http2ServerChannelHandler.handleRequest(Http2ServerChannelHandler.java:205)
	at com.alipay.sofa.rpc.transport.http.Http2ServerChannelHandler.onDataRead(Http2ServerChannelHandler.java:131)
	at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36)
	at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:292)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
	at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
