### ISSUE TITLE
com.alipay.remoting.exception.SerializationException: Serializer Not Found :"1"!

### ISSUE THREAD

**Issue by uugit** [alipay/sofa-rpc#568]
### Your question

```java
com.alipay.sofa.rpc.core.exception.SofaRpcException: com.alipay.remoting.exception.SerializationException: Serializer Not Found :"1"!
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.convertToRpcException(BoltClientTransport.java:336)
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.syncSend(BoltClientTransport.java:251)
	at com.alipay.sofa.rpc.client.AbstractCluster.doSendMsg(AbstractCluster.java:514)
	at com.alipay.sofa.rpc.client.AbstractCluster.sendMsg(AbstractCluster.java:485)
	at com.alipay.sofa.rpc.filter.ConsumerInvoker.invoke(ConsumerInvoker.java:60)
	at com.alipay.sofa.rpc.filter.sofatracer.ConsumerTracerFilter.invoke(ConsumerTracerFilter.java:66)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
	at com.alipay.sofa.rpc.filter.RpcReferenceContextFilter.invoke(RpcReferenceContextFilter.java:80)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
	at com.alipay.sofa.rpc.filter.ConsumerExceptionFilter.invoke(ConsumerExceptionFilter.java:37)
	at com.alipay.sofa.rpc.filter.FilterInvoker.invoke(FilterInvoker.java:96)
	at com.alipay.sofa.rpc.filter.FilterChain.invoke(FilterChain.java:262)
	at com.alipay.sofa.rpc.client.AbstractCluster.filterChain(AbstractCluster.java:478)            
	at com.alipay.sofa.rpc.client.FailoverCluster.doInvoke(FailoverCluster.java:66)
	at com.alipay.sofa.rpc.client.AbstractCluster.invoke(AbstractCluster.java:285)
	at com.alipay.sofa.rpc.client.ClientProxyInvoker.invoke(ClientProxyInvoker.java:83)
        ......
        .......
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.alipay.remoting.exception.SerializationException: Serializer Not Found :"1"!
	at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.serializeContent(SofaRpcSerialization.java:206)
	at com.alipay.remoting.rpc.protocol.RpcRequestCommand.serializeContent(RpcRequestCommand.java:124)
	at com.alipay.remoting.rpc.RpcCommand.serialize(RpcCommand.java:105)
	at com.alipay.remoting.rpc.RpcRemoting.toRemotingCommand(RpcRemoting.java:354)
	at com.alipay.remoting.rpc.RpcRemoting.invokeSync(RpcRemoting.java:179)
	at com.alipay.remoting.rpc.RpcClientRemoting.invokeSync(RpcClientRemoting.java:67)
	at com.alipay.remoting.rpc.RpcClient.invokeSync(RpcClient.java:350)
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.doInvokeSync(BoltClientTransport.java:275)
	at com.alipay.sofa.rpc.transport.bolt.BoltClientTransport.syncSend(BoltClientTransport.java:248)
	... 26 common frames omitted
Caused by: com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: Serializer Not Found :"1"!
	at com.alipay.sofa.rpc.codec.SerializerFactory.getSerializer(SerializerFactory.java:84)
	at com.alipay.sofa.rpc.codec.bolt.SofaRpcSerialization.serializeContent(SofaRpcSerialization.java:200)
	... 34 common frames omitted
```

### Your scenes

When the client sends a message to the server, it will report this error.

### Your advice

idea

### Environment

- SOFARPC version: 5.5.2
- JVM version (e.g. `java -version`): java10
- OS version (e.g. `uname -a`): mac 
- Maven version: 3.3
- IDE version: 2018.3.1

**Comment by leizhiyuan** [comment]
能否提供demo 看一下？

**Comment by uugit** [comment]
通过打断点 11 是protobuf, 12 是json, 那1 是什么, 这块为什么会是1, 这个需要指定么?

**Comment by leizhiyuan** [comment]
1 是hessian2， 默认的

**Comment by uugit** [comment]
create com.alipay.sofa.rpc.codec.sofa hessian.Sofa HessianSerializer instance error

**Comment by leizhiyuan** [comment]
debug 一下，看看家具体是啥错误导致的

怀疑是你hessian版本冲突。

**Comment by uugit** [comment]
![rpc](https://user-images.githubusercontent.com/6504355/55883927-c0ab6680-5bd9-11e9-8134-eda19ac5ba4b.png)

**Comment by leizhiyuan** [comment]
5.5.2 里面 bolt 还是要 以来 我们自己的hessian ，你看下你hessian的版本。

在560才会改掉。

**Comment by uugit** [comment]
这个代码里依赖的, 没关系么 
![rpc1](https://user-images.githubusercontent.com/6504355/55884352-8393a400-5bda-11e9-86b3-a71d2ce70ee7.png)

**Comment by leizhiyuan** [comment]
你就看下你的hessian版本。

**Comment by uugit** [comment]
com.alipay.sofa.hessian.4.0.1   还有一个 com.caucho.hessian.4.0.38

**Comment by leizhiyuan** [comment]
com.caucho.hessian.4.0.38 这个排除掉

**Comment by uugit** [comment]
已经OK了, 感谢!!!
