### ISSUE TITLE
NacosRegistry instance error

### ISSUE THREAD

**Issue by 9599110** [alipay/sofa-rpc#590]
### Your question

客户端使用nacos发现服务，启动抛出以下异常，麻烦大佬给看看！谢谢！

2019-04-24 15:43:22.950 ERROR [main][?:?]:[ | ]Uncaught Exception in thread 'main'com.alipay.sofa.rpc.core.exception.SofaRpcRuntimeException: create com.alipay.sofa.rpc.registry.nacos.NacosRegistry instance error
	at com.alipay.sofa.rpc.ext.ExtensionClass.getExtInstance(ExtensionClass.java:115)
	at com.alipay.sofa.rpc.registry.RegistryFactory.getRegistry(RegistryFactory.java:73)
	at com.alipay.sofa.rpc.bootstrap.DefaultConsumerBootstrap.subscribeFromRegistries(DefaultConsumerBootstrap.java:327)
	at com.alipay.sofa.rpc.bootstrap.DefaultConsumerBootstrap.subscribe(DefaultConsumerBootstrap.java:261)
	at com.alipay.sofa.rpc.client.AbstractCluster.init(AbstractCluster.java:144)
	at com.alipay.sofa.rpc.bootstrap.DefaultConsumerBootstrap.refer(DefaultConsumerBootstrap.java:152)
	at com.alipay.sofa.rpc.config.ConsumerConfig.refer(ConsumerConfig.java:925)

配置：
      "protocol": "nacos",
      "address": "127.0.0.1:8848"

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFARPC version: 
             引入的：sofa-rpc-all   版本：5.5.2
- JVM version (e.g. `java -version`): 
            JDK1.8
- OS version (e.g. `uname -a`):
            MAC 10.12.3
- Maven version:  
            apache-maven-3.5.2
- IDE version:

**Comment by leizhiyuan** [comment]
引入了nacos 什么版本？

**Comment by 9599110** [comment]
找到原因了，需要引入nacos库，加以下pom配置问题解决了！
		<dependency>
		    <groupId>com.alibaba.nacos</groupId>
		    <artifactId>nacos-client</artifactId>
		    <version>1.0.0</version>
		</dependency>

**Comment by leizhiyuan** [comment]
ok， nacos 作为provided 依赖。使用需要用户自己引入。

**Comment by khotyn** [comment]
@leizhiyuan Can we improve the [document](https://www.sofastack.tech/sofa-rpc/docs/Registry-Nacos) ? Remind users to add corresponding dependencies.

**Comment by leizhiyuan** [comment]
ok，i will change the doc
